---
apiVersion: apiserver.config.k8s.io/v1
kind: AuthorizationConfiguration
authorizers:
  - type: Webhook
    name: crlish
    webhook:
      authorizedTTL: 90s
      unauthorizedTTL: 300s
      timeout: 3s
      subjectAccessReviewVersion: v1
      matchConditionSubjectAccessReviewVersion: v1
      failurePolicy: NoOpinion
      connectionInfo:
        type: KubeConfigFile
        kubeConfigFile: /etc/kubernetes/webhook_crlish-authorizer.yaml
      matchConditions:
        - expression: "'authentication.kubernetes.io/credential-id' in request.extra"
  - type: Node
    name: node
  - type: RBAC
    name: rbac
