---
apiVersion: v1
kind: Config
clusters:
  - name: crlish-authorizer
    cluster:
      certificate-authority: /etc/kubernetes/pki/ca.crt
      server: https://crlish-authorizer.crlish-authorizer.svc.cluster.local/
contexts:
  - name: crlish-authorizer
    context:
      cluster: crlish-authorizer
current-context: crlish-authorizer
